# Generated by Django 4.2.13 on 2024-05-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Published'), ('d', 'Draft')], default='d', max_length=1, null=True, verbose_name='Status (*)'),
        ),
    ]
